// Pass 83 — CFGLinearization (Phase 8: Lowering & Machine Optimization)
//
// Lays the SoN graph out into ordered basic blocks:
//   * RPO over the control graph (reachable blocks only; hot-path
//     preference = loop bodies contiguous with headers, branch layout
//     decided at emission using BranchProb)
//   * per-block topological scheduling: memory chain defines the effect
//     order; pure nodes are ordered uses-after-defs within the block
//   * phi moves attached to predecessor block ends (parallel-copy semantics
//     approximated by sequential moves; swap cycles are not generated by
//     the MVP frontend)
#include "core/codegen/linear.h"
#include "core/son/passes/pass_utils.h"

namespace jules {

namespace {
class Linearizer {
public:
    Linearizer(FunctionGraph& fg, DomTree& dom) : fg_(fg), dom_(dom) {}

    bool run(LFunction& lf) {
        lf.fid = fg_.fid;
        lf.name = fg_.name;
        lf.ret = fg_.ret;
        lf.params = fg_.param_types;

        // blocks in RPO of control heads
        FlatMap<NodeId, bool> seen;
        for (NodeId head : dom_.rpo()) {
            if (!is_block_head(fg_.g.node(head).op)) continue;
            LBlock b;
            b.head = head;
            b.index = static_cast<int>(lf.blocks.size());
            lf.blocks.push_back(b);
            block_index_.insert(head, b.index);
        }

        // content + terminators
        for (LBlock& b : lf.blocks) {
            collect_block(b);
        }

        // successors / predecessors
        for (LBlock& b : lf.blocks) {
            attach_successors(b);
        }
        for (LBlock& b : lf.blocks) {
            for (int s : b.succs) lf.blocks[static_cast<size_t>(s)].preds.push_back(b.index);
        }

        // phi copies: region R, phi P, pred i -> copy at pred block end
        for (LBlock& b : lf.blocks) {
            const Node& head = fg_.g.node(b.head);
            if (head.op != Op::Region) continue;
            for (NodeId u : fg_.g.uses_of(b.head)) {
                const Node& un = fg_.g.node(u);
                if (un.op != Op::Phi || un.ty == ty_mem()) continue;
                for (u8 i = 0; i < head.n_in; ++i) {
                    const i32* pb = block_index_.find(head.in[i]);
                    if (!pb) continue;
                    LPhiCopy cp;
                    cp.src = un.in[i + 1];
                    cp.dst = u;
                    lf.phi_copies.push_back(cp);
                    lf.blocks[static_cast<size_t>(*pb)].phi_copy_indices.push_back(
                        static_cast<int>(lf.phi_copies.size()) - 1);
                }
            }
        }
        return !lf.blocks.empty();
    }

private:
    void collect_block(LBlock& b) {
        Graph& g = fg_.g;
        std::vector<NodeId> pinned;
        for (NodeId u : g.uses_of(b.head)) {
            Node& un = g.node(u);
            if (un.op == Op::Dead) continue;
            if (un.in[0] != b.head) continue; // used as pred/other, not pinned
            if (un.op == Op::If) { b.terminator_if = u; continue; }
            if (un.op == Op::Return) { b.terminator_return = u; continue; }
            if (un.op == Op::Jump) { b.jump = u; continue; } // unusual: pinned jump
            if (is_block_head(un.op)) continue;
            pinned.push_back(u);
        }
        if (b.jump != kNoNode) {
            // this block's head is itself a Jump node: also gather pinned nodes
        }

        // topological schedule: Kahn with data + memory edges inside the block
        FlatMap<NodeId, bool> placed;
        std::vector<NodeId> order;
        for (u32 round = 0; round < pinned.size() + 1 && order.size() < pinned.size(); ++round) {
            bool progressed = false;
            for (NodeId n : pinned) {
                if (placed.contains(n)) continue;
                bool ready = true;
                const Node& nd = g.node(n);
                for (u8 i = 1; i < nd.n_in && ready; ++i) {
                    NodeId d = nd.in[i];
                    if (d == kNoNode || g.node(d).op == Op::Dead) continue;
                    if (g.node(d).in[0] == b.head && !is_block_head(g.node(d).op) &&
                        d != n && !placed.contains(d))
                        ready = false;
                }
                if (ready) {
                    placed.insert(n, true);
                    order.push_back(n);
                    progressed = true;
                }
            }
            if (!progressed) {
                // cycle or cross-block oddity: append the rest in id order
                for (NodeId n : pinned)
                    if (!placed.contains(n)) { order.push_back(n); placed.insert(n, true); }
                break;
            }
        }
        b.nodes = order;
    }

    void attach_successors(LBlock& b) {
        Graph& g = fg_.g;
        auto add = [&](NodeId head) {
            const i32* idx = block_index_.find(head);
            if (idx) b.succs.push_back(*idx);
        };
        if (b.terminator_return != kNoNode) return; // terminal
        if (b.terminator_if != kNoNode) {
            for (NodeId p : g.uses_of(b.terminator_if)) {
                Op po = g.node(p).op;
                if (po == Op::IfTrue || po == Op::IfFalse) add(p);
            }
            return;
        }
        if (g.node(b.head).op == Op::Jump) {
            // falls to regions using this jump as pred
            for (NodeId u : g.uses_of(b.head)) {
                if (g.node(u).op == Op::Region && g.node(u).op != Op::Dead) {
                    // only direct region preds
                    const Node& r = g.node(u);
                    bool is_pred = false;
                    for (u8 i = 0; i < r.n_in; ++i)
                        if (r.in[i] == b.head) is_pred = true;
                    if (is_pred) add(u);
                }
            }
            return;
        }
        // plain block: falls to regions using head as pred
        for (NodeId u : g.uses_of(b.head)) {
            if (g.node(u).op != Op::Region) continue;
            const Node& r = g.node(u);
            for (u8 i = 0; i < r.n_in; ++i)
                if (r.in[i] == b.head) { add(u); break; }
        }
    }

    FunctionGraph& fg_;
    DomTree& dom_;
    FlatMap<NodeId, i32> block_index_;
};
} // namespace

class CFGLinearizationPass : public Pass {
public:
    const char* name() const override { return "CFGLinearization"; }
    int order() const override { return 83; }
    const char* phase_name() const override { return "Phase 8: Lowering & Machine Optimization"; }
    Stage stage() const override { return Stage::Linear; }
    AnalysisMask required() const override { return static_cast<AnalysisMask>(AnalysisKind::Dominators); }
    AnalysisMask invalidated() const override { return 0; }
    bool run(PassContext& ctx) override {
        if (!ctx.lin) return false;
        ctx.lin->fns.clear();
        bool ok = true;
        for (FunctionGraph& fg : ctx.mod.fns) {
            if (fg.is_comptime) continue; // comptime fns never execute at runtime
            LFunction lf;
            Linearizer l(fg, ctx.analysis.doms(fg));
            ok &= l.run(lf);
            lf.is_main = ctx.syms.name(fg.name) == "main";
            ctx.lin->fns.push_back(std::move(lf));
        }
        return ok;
    }
};

JULES_REGISTER_PASS(CFGLinearizationPass, 83, "Phase 8")

} // namespace jules
