// Pass 83 — CFGLinearization (Phase 8: Lowering & Machine Optimization)
//
// Lays the SoN graph out into ordered basic blocks:
//   * RPO over the control graph (reachable blocks only; hot-path
//     preference = loop bodies contiguous with headers, branch layout
//     decided at emission using BranchProb)
//   * per-block topological scheduling: memory chain defines the effect
//     order; pure nodes are ordered uses-after-defs within the block
//   * phi moves attached to predecessor block ends (parallel-copy semantics
//     approximated by sequential moves; swap cycles are not generated by
//     the MVP frontend)
#include "core/codegen/linear.h"
#include "core/son/passes/pass_utils.h"

namespace jules {

namespace {
class Linearizer {
public:
    Linearizer(FunctionGraph& fg, DomTree& dom) : fg_(fg), dom_(dom) {}

    bool run(LFunction& lf) {
        lf.fid = fg_.fid;
        lf.name = fg_.name;
        lf.ret = fg_.ret;
        lf.params = fg_.param_types;
        cur_lf_ = &lf;

        // blocks in RPO of control heads
        FlatMap<NodeId, bool> seen;
        for (NodeId head : dom_.rpo()) {
            if (!is_block_head(fg_.g.node(head).op)) continue;
            LBlock b;
            b.head = head;
            b.index = static_cast<int>(lf.blocks.size());
            lf.blocks.push_back(b);
            block_index_.insert(head, b.index);
        }

        // content + terminators
        for (LBlock& b : lf.blocks) {
            collect_block(b);
        }

        // successors / predecessors
        for (LBlock& b : lf.blocks) {
            attach_successors(b);
        }
        for (LBlock& b : lf.blocks) {
            for (int s : b.succs) lf.blocks[static_cast<size_t>(s)].preds.push_back(b.index);
        }

        // phi copies: region R, phi P, pred i -> copy at pred block end
        for (LBlock& b : lf.blocks) {
            const Node& head = fg_.g.node(b.head);
            if (head.op != Op::Region) continue;
            for (NodeId u : fg_.g.uses_of(b.head)) {
                const Node& un = fg_.g.node(u);
                if (un.op != Op::Phi || un.ty == ty_mem()) continue;
                for (u8 i = 0; i < head.n_in; ++i) {
                    const i32* pb = block_index_.find(head.in[i]);
                    if (!pb) continue;
                    LPhiCopy cp;
                    cp.src = un.in[i + 1];
                    cp.dst = u;
                    lf.phi_copies.push_back(cp);
                    lf.blocks[static_cast<size_t>(*pb)].phi_copy_indices.push_back(
                        static_cast<int>(lf.phi_copies.size()) - 1);
                }
            }
        }
        return !lf.blocks.empty();
    }

private:
    void collect_block(LBlock& b) {
        Graph& g = fg_.g;
        std::vector<NodeId> pinned;
        for (NodeId u : g.uses_of(b.head)) {
            Node& un = g.node(u);
            if (un.op == Op::Dead) continue;
            if (un.in[0] != b.head) continue; // used as pred/other, not pinned
            if (un.op == Op::If) { b.terminator_if = u; continue; }
            if (un.op == Op::Return) { b.terminator_return = u; continue; }
            if (un.op == Op::Jump) { b.jump = u; continue; } // unusual: pinned jump
            if (is_block_head(un.op)) continue;
            pinned.push_back(u);
        }
        if (b.jump != kNoNode) {
            // this block's head is itself a Jump node: also gather pinned nodes
        }

        // topological schedule: Kahn with data + memory edges inside the block.
        //
        // Memory-ordering rule (soundness): a Load L reads the memory state
        // of its version input M (in[1]). An effect node E (Store/Call/Alloc)
        // consuming the SAME version M must execute AFTER every such load:
        // the graph asserts "L sees the world as of M", and scheduling E
        // first would let L observe E's writes (observed as loads moved
        // after free() — tcache-poisoned reads). The rule also protects
        // ancestor versions transitively: effects wait for same-version
        // loads, and versions chain, so older loads block the intermediate
        // effects first.
        FlatMap<NodeId, bool> placed;
        std::vector<NodeId> order;
        FlatMap<NodeId, std::vector<NodeId>> loads_of_version; // mem version -> loads
        for (NodeId n : pinned)
            if (g.node(n).op == Op::Load)
                loads_of_version[g.node(n).in[1]].push_back(n);
        auto mem_order_ok = [&](NodeId n) {
            const Node& nd = g.node(n);
            if (!is_effect_op(nd.op)) return true;
            const std::vector<NodeId>* ls = loads_of_version.find(nd.in[1]);
            if (!ls) return true;
            for (NodeId l : *ls)
                if (l != n && !placed.contains(l)) return false;
            return true;
        };
        const bool dbg = getenv("JULES_DEBUG_LIN") != nullptr;
        for (u32 round = 0; round < pinned.size() + 1 && order.size() < pinned.size(); ++round) {
            bool progressed = false;
            for (NodeId n : pinned) {
                if (placed.contains(n)) continue;
                bool ready = true;
                const Node& nd = g.node(n);
                for (u8 i = 1; i < nd.n_in && ready; ++i) {
                    NodeId d = nd.in[i];
                    if (d == kNoNode || g.node(d).op == Op::Dead) continue;
                    if (g.node(d).in[0] == b.head && !is_block_head(g.node(d).op) &&
                        d != n && !placed.contains(d))
                        ready = false;
                }
                if (ready) ready = mem_order_ok(n);
                if (dbg && !ready) {
                    std::fprintf(stderr, "[lin] b%d r%u n%u(%s) blocked by:", b.index, round, n,
                                 op_name(g.node(n).op));
                    for (u8 i = 1; i < nd.n_in; ++i) {
                        NodeId d = nd.in[i];
                        if (d == kNoNode || g.node(d).op == Op::Dead) continue;
                        if (g.node(d).in[0] == b.head && !is_block_head(g.node(d).op) &&
                            d != n && !placed.contains(d))
                            std::fprintf(stderr, " n%u(%s)", d, op_name(g.node(d).op));
                    }
                    if (!mem_order_ok(n)) std::fprintf(stderr, " <mem-order>");
                    std::fprintf(stderr, "\n");
                }
                if (ready) {
                    placed.insert(n, true);
                    order.push_back(n);
                    progressed = true;
                }
            }
            if (!progressed) {
                // cycle or cross-block oddity: append the rest in id order
                for (NodeId n : pinned)
                    if (!placed.contains(n)) { order.push_back(n); placed.insert(n, true); }
                break;
            }
        }
        b.nodes = order;
        if (getenv("JULES_DEBUG_LIN")) {
            std::fprintf(stderr, "[lin] block b%d head n%u:", b.index, b.head);
            for (NodeId n : b.nodes)
                std::fprintf(stderr, " n%u(%s)", n, op_name(g.node(n).op));
            std::fprintf(stderr, "\n");
        }
    }

    void attach_successors(LBlock& b) {
        Graph& g = fg_.g;
        auto add = [&](NodeId head) {
            const i32* idx = block_index_.find(head);
            if (idx) b.succs.push_back(*idx);
        };
        if (b.terminator_return != kNoNode) return; // terminal
        if (b.terminator_if != kNoNode) {
            for (NodeId p : g.uses_of(b.terminator_if)) {
                Op po = g.node(p).op;
                if (po == Op::IfTrue || po == Op::IfFalse) add(p);
            }
        } else if (g.node(b.head).op == Op::Jump) {
            // falls to regions using this jump as pred
            for (NodeId u : g.uses_of(b.head)) {
                if (g.node(u).op == Op::Region && g.node(u).op != Op::Dead) {
                    // only direct region preds
                    const Node& r = g.node(u);
                    bool is_pred = false;
                    for (u8 i = 0; i < r.n_in; ++i)
                        if (r.in[i] == b.head) is_pred = true;
                    if (is_pred) add(u);
                }
            }
        } else {
            // plain block: falls to regions using head as pred
            for (NodeId u : g.uses_of(b.head)) {
                if (g.node(u).op != Op::Region) continue;
                const Node& r = g.node(u);
                for (u8 i = 0; i < r.n_in; ++i)
                    if (r.in[i] == b.head) { add(u); break; }
            }
        }
        // FALLTHROUGH EDGE (all cases above): a block whose successor list
        // came out EMPTY still transfers control — the emitter emits no
        // jump for empty succs (plain blocks, Jump heads whose region
        // users died, and If terminators whose projections died after
        // inlining — the leftover If records no edges and the block simply
        // falls through to the next one in the layout). Without the edge
        // here the register allocator's liveness dataflow loses the path:
        // values used after the fallthrough (a loop-exit reader) are not
        // live around the loop backedge, and the loop body redefines their
        // registers — the classic miscompile: a value defined before a
        // loop, read after it, clobbered by the body (found by the pass
        // audit: always-inlined copy loops over loop-filled arrays
        // segfaulted on the stale base pointer).
        if (b.succs.empty()) {
            LFunction& lf = *cur_lf_;
            if (b.index + 1 < static_cast<i32>(lf.blocks.size()))
                b.succs.push_back(b.index + 1);
        }
    }

    LFunction* cur_lf_ = nullptr;

    FunctionGraph& fg_;
    DomTree& dom_;
    FlatMap<NodeId, i32> block_index_;
};
} // namespace

class CFGLinearizationPass : public Pass {
public:
    const char* name() const override { return "CFGLinearization"; }
    int order() const override { return 83; }
    const char* phase_name() const override { return "Phase 8: Lowering & Machine Optimization"; }
    Stage stage() const override { return Stage::Linear; }
    AnalysisMask required() const override { return static_cast<AnalysisMask>(AnalysisKind::Dominators); }
    AnalysisMask invalidated() const override { return 0; }
    bool run(PassContext& ctx) override {
        if (!ctx.lin) return false;
        ctx.lin->fns.clear();
        bool ok = true;
        // Module-level dead-function elimination: after inlining, functions
        // with no remaining callers from main are unreachable in a closed
        // module (no shared-library exports, comptime fns excluded already).
        // Reachability = fixpoint over live Call nodes' FnIds from main.
        FlatMap<FnId, bool> reachable;
        std::vector<FnId> work;
        bool have_root = false;
        for (FunctionGraph& fg : ctx.mod.fns) {
            if (fg.is_comptime) continue;
            if (ctx.syms.name(fg.name) == "main") {
                reachable.insert(fg.fid, true);
                work.push_back(fg.fid);
                have_root = true;
                break;
            }
        }
        if (!work.empty()) {
            FlatMap<FnId, FunctionGraph*> by_fid;
            for (FunctionGraph& fg : ctx.mod.fns) by_fid.insert(fg.fid, &fg);
            while (!work.empty()) {
                FnId f = work.back();
                work.pop_back();
                FunctionGraph** fgp = by_fid.find(f);
                if (!fgp) continue;
                for (NodeId n = 0; n < (*fgp)->g.size(); ++n) {
                    const Node& nd = (*fgp)->g.node(n);
                    if (nd.op != Op::Call) continue; // killed nodes are Dead
                    if (nd.aux == kFnPrint || nd.aux == kFnFree) continue; // external
                    const bool* seen = reachable.find(static_cast<FnId>(nd.aux));
                    if (!seen) {
                        reachable.insert(static_cast<FnId>(nd.aux), true);
                        work.push_back(static_cast<FnId>(nd.aux));
                    }
                }
            }
        }
        for (FunctionGraph& fg : ctx.mod.fns) {
            if (fg.is_comptime) continue; // comptime fns never execute at runtime
            if (have_root && !reachable.contains(fg.fid)) continue; // dead fn
            LFunction lf;
            Linearizer l(fg, ctx.analysis.doms(fg));
            ok &= l.run(lf);
            lf.is_main = ctx.syms.name(fg.name) == "main";
            ctx.lin->fns.push_back(std::move(lf));
        }
        return ok;
    }
};

JULES_REGISTER_PASS(CFGLinearizationPass, 83, "Phase 8")

} // namespace jules
